// Korean UI-string dictionary, keyed by the exact English source string.
// Generated from the translation pass; hand-editable. Missing keys fall back to English.
export const KO: Record<string, string> = {
  "7D": "7일",
  "30D": "30일",
  "All time": "전체 기간",
  "Verifiable Intent, built in.": "Verifiable Intent가 기본적으로 내장되어 있습니다.",
  "Every agent payment on the hub can carry Mastercard Verifiable Intent — credentialed, consent-bound payments from Agent Pay for Machines — enforced by t54’s x402 Secure before it settles.": "허브에서 발생하는 모든 에이전트 결제는 Mastercard Verifiable Intent를 포함할 수 있습니다. 이는 Agent Pay for Machines가 제공하는 자격 증명 및 사용자 동의 기반의 결제 방식입니다. 모든 결제는 정산되기 전, t54의 x402 Secure를 통해 검증 및 승인 절차를 반드시 거치게 됩니다.",
  "XRPL · AI hub": "XRPL · AI 허브",
  "Build the agent economy on XRP Ledger": "XRP Ledger 위에서 AI 에이전트 경제를",
  "together": "함께 만듭니다",
  "An open community of builders, agents, and services growing on the XRP Ledger — where agents transact in XRP and RLUSD.": "XRPL AI Hub는 개발자와 AI 에이전트, 그리고 다양한 서비스가 XRP Ledger 생태계에서 함께 성장하는 열린 커뮤니티입니다. 본 생태계에서 AI 에이전트는 XRP와 RLUSD로 거래합니다.",
  "Join the community": "커뮤니티 참여하기",
  "Explore the directory": "디렉터리 둘러보기",
  "Get listed": "서비스 등록하기",
  "Quickstart": "바로 시작하기",
  "Live": "라이브",
  "No API keys, no custody — just plug and play. Supports XRP and IOU tokens (RLUSD, USDC) with presigned payment verification and settlement.": "API 키 발급이나 자산 수탁 없이, 연결 즉시 바로 사용할 수 있습니다. 미리 서명된 결제의 검증 및 정산을 지원하며, XRP는 물론 RLUSD, USDC 등 다양한 IOU 토큰 거래가 가능합니다.",
  "Get Started": "시작하기",
  "Docs": "문서",
  "API resource": "API 서비스",
  "Per call →": "호출당 →",
  "No services indexed yet.": "아직 집계된 서비스가 없습니다.",
  "List the first one →": "첫 번째 서비스를 등록해 보세요 →",
  "Directory": "디렉터리",
  "{n} live x402 services · pay per call in RLUSD or XRP": "라이브 x402 서비스 {n}개 · 호출할 때마다 RLUSD 또는 XRP로 결제",
  "Browse all →": "전체 보기 →",
  "Live settlements": "실시간 정산",
  "verified before settle · on the spine": "정산 전 검증 · 렛저에 기록",
  "View All →": "전체 보기 →",
  "24h": "24시간",
  "7d": "7일",
  "Top Merchants": "상위 머천트(Merchant)",
  "Loading…": "불러오는 중…",
  "Couldn’t load merchants — try again in a moment.": "머천트 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.",
  "No merchant activity in this window yet.": "이 기간에는 아직 머천트 활동이 없습니다.",
  "txns": "건",
  "XRP settled": "XRP 정산액",
  "RLUSD settled": "RLUSD 정산액",
  "Transactions": "트랜잭션",
  "Merchants": "머천트",
  "NEW": "신규",
  "Total settled": "총 정산액",
  "verification: delegation pair, signature, seal": "검증 항목: 권한 위임 확인, 전자 서명, 위·변조 방지 봉인",
  "View transaction details": "트랜잭션 상세 보기",
  "No settlements indexed yet.": "아직 집계된 정산 내역이 없습니다.",
  "Ecosystem": "생태계",
  "News": "뉴스",
  "news": "뉴스",
  "post": "게시글",
  "open ↗": "열기 ↗",
  "Scroll left": "왼쪽으로 스크롤",
  "Scroll right": "오른쪽으로 스크롤",
  "No resources registered for this merchant.": "이 머천트에 등록된 서비스가 없습니다.",
  "Unnamed resource": "이름 없는 서비스",
  "Active": "활성",
  "Inactive": "비활성",
  "Prev": "이전",
  "Next": "다음",
  "Page {current} of {total} · {count} APIs": "{total}페이지 중 {current}페이지 · API {count}개",
  "Search": "검색",
  "Search by address or transaction hash": "주소 또는 트랜잭션 해시(트랜잭션 고유 번호)로 검색",
  "Search by address or tx hash...": "주소 또는 트랜잭션 해시(트랜잭션 고유 번호)로 검색...",
  "Cookies & analytics": "쿠키와 분석 안내",
  "We use Google Analytics to understand how the hub is used so we can improve it. It’s anonymous, there is no advertising, and we never sell or share your data. Accept to help us, or decline to keep analytics off — you can change your choice anytime under": "저희는 허브가 어떻게 사용되는지 알아보고 개선하기 위해 Google Analytics를 사용합니다. 수집되는 정보는 익명이며, 광고에 쓰이지 않고, 여러분의 데이터를 판매하거나 공유하는 일은 없습니다. 수락을 누르시면 개선에 도움이 되고, 거부를 누르시면 분석 기능이 꺼진 채 유지됩니다. 선택은 언제든지 페이지 하단의",
  "Cookie settings": "쿠키 설정",
  "in the footer. See our": "메뉴에서 바꿀 수 있습니다. 자세한 내용은 다음 문서를 확인해 주세요:",
  "Privacy Policy": "개인정보 처리방침",
  "Decline": "거부",
  "Accept": "수락",
  "Verified": "검증됨",
  "Unverified": "미검증",
  "Verifiable Intent — verified": "Verifiable Intent — 검증됨",
  "Unverified intent": "결제 의도 미검증",
  "This payment carried a Mastercard Verifiable Intent chain — a signed, consent-bound authorization from the paying agent — and cleared t54's x402 Secure risk checks before it settled on the XRP Ledger.": "이 결제에는 Mastercard Verifiable Intent 승인 기록이 담겨 있었습니다. 결제하는 AI 에이전트가 서명하고 사용자 동의에 근거해 승인한 것입니다. 이 결제는 XRP Ledger에서 정산되기 전에 t54의 x402 Secure 위험 검사를 통과했습니다.",
  "This payment carried a Mastercard Verifiable Intent chain — a signed, consent-bound authorization from the paying agent — verified before it settled on the XRP Ledger.": "이 결제에는 Mastercard Verifiable Intent 승인 기록이 담겨 있었습니다. 결제하는 AI 에이전트가 서명하고 사용자 동의에 근거해 승인한 것으로, XRP Ledger에서 정산되기 전에 검증되었습니다.",
  "A valid XRPL x402 payment, but it settled without a Mastercard Verifiable Intent chain — no signed authorization or x402 Secure risk gating was attached.": "유효한 XRPL x402 결제이지만, Mastercard Verifiable Intent 승인 기록 없이 정산되었습니다. 서명된 승인도, x402 Secure의 위험 심사도 붙어 있지 않았습니다.",
  "How to get your payments verified": "결제를 검증받는 방법",
  "Add Verifiable Intent to your payments": "결제에 Verifiable Intent 추가하기",
  "Verifiable Intent verified": "Verifiable Intent 검증됨",
  "Copied": "복사됨",
  "Copy to clipboard": "클립보드에 복사",
  "just now": "방금 전",
  "{n}s ago": "{n}초 전",
  "{n}m ago": "{n}분 전",
  "{n}h ago": "{n}시간 전",
  "{n}d ago": "{n}일 전",
  "Not Found": "찾을 수 없음",
  "The page, address, or transaction you’re looking for doesn’t exist.": "찾으시는 페이지, 주소 또는 트랜잭션가 존재하지 않습니다.",
  "Back to Dashboard": "메인 화면으로 돌아가기",
  "Something went wrong": "문제가 발생했습니다",
  "An unexpected error occurred.": "예상치 못한 오류가 발생했습니다.",
  "Try again": "다시 시도",
  "T54 Labs Inc. is an official launch partner of Mastercard’s Agent Pay for Machines. Mastercard, Mastercard Agent Pay, Agent Pay for Machines and Verifiable Intent are trademarks of Mastercard International Incorporated.": "T54 Labs Inc.는 Mastercard의 Agent Pay for Machines 공식 론칭 파트너입니다. Mastercard, Mastercard Agent Pay, Agent Pay for Machines 및 Verifiable Intent는 Mastercard International Incorporated의 상표입니다.",
  "Who’s building": "XRPL 생태계의",
  "on the rail": "빌더들",
  "Live x402 services and the merchants settling on XRPL — indexed from mainnet, in RLUSD and XRP.": "XRPL 메인넷 온체인 데이터를 기반으로 집계된 x402 서비스 및 제공사 현황입니다. 모든 결제와 정산은 RLUSD 및 XRP로 처리됩니다.",
  "Page {page} of {pages}": "{pages}페이지 중 {page}페이지",
  "Services": "서비스",
  "Live x402 endpoints that agents can pay to use, indexed from XRPL mainnet.": "AI 에이전트가 요금을 지불하고 이용할 수 있는 라이브 x402 엔드포인트입니다. XRPL 메인넷을 기반으로 인덱싱했습니다.",
  "{n} services": "서비스 {n}개",
  "Addresses settling x402 payments on XRPL, ranked by transaction count.": "XRPL에서 x402 결제를 정산하는 주소를 트랜잭션 수 순으로 보여드립니다.",
  "No merchants indexed yet.": "아직 집계된 머천트이 없습니다.",
  "{n} merchants": "머천트 {n}개",
  "API provider": "API 제공자",
  "Pay-per-call x402 endpoint at {host}.": "{host}의 호출당 결제 x402 엔드포인트입니다.",
  "Discovered": "발견됨",
  "Registered": "등록됨",
  "from {price}": "{price}부터",
  "{n} endpoint": "엔드포인트 {n}개",
  "{n} endpoints": "엔드포인트 {n}개",
  "{n} txns": "트랜잭션 {n}건",
  "XRPL merchant": "XRPL 머천트",
  "{n} svc": "서비스 {n}개",
  "All": "전체",
  "Verified 402": "402 검증됨",
  "Ledger History": "렛저 기록",
  "Real-time x402 payment confirmations on the XRPL": "XRPL 렛저(모든 거래가 기록되는 장부)에 실시간으로 올라오는 x402 결제 확인 내역입니다",
  "{n} total transactions": "총 트랜잭션 {n}건",
  "No x402 transactions found on the ledger yet.": "아직 렛저에 기록된 x402 트랜잭션가 없습니다.",
  "Transaction Hash": "트랜잭션 해시",
  "Time": "시간",
  "Intent": "결제 의도",
  "Merchant / Resource": "머천트 / 서비스",
  "Buyer": "구매자",
  "Value": "금액",
  "Previous": "이전",
  "Page {page} of {total}": "{total}페이지 중 {page}페이지",
  "All transactions": "전체 트랜잭션",
  "Transaction": "트랜잭션",
  "Transaction details": "트랜잭션 상세 정보",
  "Amount": "금액",
  "Intent status": "결제 의도 상태",
  "Transaction hash": "트랜잭션 해시",
  "Ledger index": "렛저 번호",
  "Timestamp": "기록 시각",
  "Asset issuer": "자산 발행자",
  "Merchant": "머천트",
  "Resource": "서비스",
  "Destination tag": "Destination Tag(수신 식별 번호)",
  "Source tag": "Source Tag(발신 식별 번호)",
  "Invoice ID": "인보이스 ID",
  "Facilitator": "Facilitator(결제 중개)",
  "Raw memo": "원본 메모",
  "View on XRPL Explorer": "XRPL Explorer에서 보기",
  "Unknown merchant": "알 수 없는 머천트",
  "Website": "웹사이트",
  "Transactions over time": "시간별 트랜잭션 추이",
  "Total volume": "총 거래량",
  "Payments received": "받은 결제",
  "Active APIs": "활성 API",
  "Joined": "가입일",
  "Offered APIs": "제공 중인 API",
  "Recent payments": "최근 결제",
  "Buyer address": "구매자 주소",
  "Total spent": "총 지출",
  "Payments made": "보낸 결제",
  "Merchants used": "이용한 머천트",
  "Payment history": "결제 내역",
  "Hash": "해시",
  "Unknown": "알 수 없음",
  "No transactions recorded yet.": "아직 기록된 트랜잭션가 없습니다.",
  "XRPL addresses receiving x402 payments": "x402 결제를 받는 XRPL 주소",
  "{n} merchant": "머천트 {n}개",
  "{n} txs": "트랜잭션 {n}건",
  "{n} resources": "서비스 {n}개",
  "No merchants found yet.": "아직 발견된 머천트이 없습니다.",
  "Address": "주소",
  "Name": "이름",
  "Resources": "서비스",
  "Real brands,": "실제 브랜드에",
  "reachable by agents": "AI 에이전트가 도달합니다",
  "We bring established merchants onto RLUSD and XRP settlement on XRPL through merchant-network partners.": "머천트 네트워크 파트너를 통해, 이미 자리 잡은 머천트들이 XRPL에서 RLUSD와 XRP로 정산하도록 연결해 드립니다.",
  "Flagship partner — CloudStore": "대표 파트너 — CloudStore",
  "in discussion": "협의 중",
  "CloudStore (nubestore.ai) is a plug-and-play agentic-checkout platform. Its existing network already includes major retailers — 500+ merchants, $1B+ GMV fulfilled. Through a CloudStore integration, established brands can settle agent purchases in RLUSD or XRP on XRPL.": "CloudStore(nubestore.ai)는 연결만 하면 바로 쓸 수 있는, AI 에이전트(사람 대신 자동으로 일하는 인공지능 프로그램) 자동 결제 플랫폼입니다. 기존 네트워크에는 이미 주요 유통 브랜드들이 참여하고 있습니다 — 머천트 500곳 이상, 누적 거래액(GMV) 10억 달러 이상을 처리했습니다. CloudStore와 연동하면 자리 잡은 브랜드도 AI 에이전트의 구매 대금을 XRPL에서 RLUSD 또는 XRP로 정산할 수 있습니다.",
  "& 500+ more": "외 500곳 이상",
  "Why a network, not one-by-one": "하나씩이 아니라 네트워크로 연결하는 이유",
  "Onboarding traditional merchants is a B2B integration, not a self-serve flow. Partnering with merchant networks brings many brands onto XRPL rails at once.": "전통적인 머천트을 연결하는 일은 기업 간(B2B) 통합 작업이지, 스스로 가입해 끝나는 절차가 아닙니다. 머천트 네트워크와 손잡으면 여러 브랜드를 한 번에 XRPL 레일로 연결할 수 있습니다.",
  "Institutional backdrop": "기관 차원의 배경",
  "Ripple is one of 30+ launch partners for Mastercard’s Agent Pay for Machines — agent commerce is arriving at the card-network scale, and XRPL — with RLUSD and XRP — is a settlement-grade rail for it.": "Ripple은 Mastercard의 Agent Pay for Machines 론칭 파트너 30여 곳 중 하나입니다. AI 에이전트 상거래는 카드 네트워크 규모로 다가오고 있습니다. RLUSD와 XRP를 갖춘 XRPL은 이 규모의 정산을 감당할 수 있는 결제망(레일)입니다.",
  "Bring your network": "네트워크를 연결하세요",
  "Run a merchant network, or a brand exploring agent commerce? Talk to us — this is a guided onboarding, not self-serve. We’ll ask about:": "머천트 네트워크를 운영하고 계신가요? 아니면 AI 에이전트 상거래를 검토 중인 브랜드이신가요? 저희에게 문의해 주세요. 스스로 진행하는 방식이 아니라, 저희가 직접 안내해 드리는 가입 절차입니다. 다음 내용을 여쭤봅니다:",
  "Company name": "회사명",
  "Estimated monthly settlement volume": "예상 월 정산 규모",
  "Current payment rails": "현재 사용 중인 결제망",
  "Target launch window": "목표 출시 시기",
  "RLUSD / XRP readiness": "RLUSD / XRP 준비 상태",
  "Region / country": "지역 / 국가",
  "BD contact": "사업 개발(BD) 담당자",
  "Contact sales": "영업팀 문의",
  "Facilitators": "Facilitator",
  "Every x402 facilitator settling on XRPL, ranked by on-chain activity. Register yours to be indexed.": "XRPL에서 정산하는 모든 x402 facilitator(결제 중개 서비스)입니다. 렛저에 기록된 활동량 순으로 정렬했습니다. 등록하시면 함께 집계됩니다.",
  "Register your facilitator": "Facilitator 등록하기",
  "No facilitators indexed yet.": "아직 집계된 facilitator가 없습니다.",
  "Txs": "거래",
  "Agents": "AI 에이전트",
  "Settled": "정산액",
  "Enter an address or transaction hash in the search bar above.": "위 검색창에 주소나 트랜잭션 해시(트랜잭션 고유 번호)를 입력해 주세요.",
  "Search Results": "검색 결과",
  "{n} result for": "다음 검색어에 대한 결과 {n}건:",
  "{n} results for": "다음 검색어에 대한 결과 {n}건:",
  "No results found. Try a different search term.": "검색 결과가 없습니다. 다른 검색어로 다시 시도해 보세요.",
  "Merchants / Addresses": "머천트 / 주소",
  "Unknown Merchant": "알 수 없는 머천트",
  "Unnamed Resource": "이름 없는 서비스",
  "Agora": "아고라",
  "Discover pay-per-use APIs and services on the XRPL x402 network.": "XRPL x402 네트워크에서 쓴 만큼만 결제하는 API와 서비스를 찾아보세요.",
  "({n} resources)": "(서비스 {n}개)",
  "No resources listed yet": "아직 등록된 서비스가 없습니다",
  "Be the first to register an x402-compatible API on the XRPL.": "XRPL에 x402 호환 API를 가장 먼저 등록해 보세요.",
  "Register Your API": "API 등록하기",
  "API Resource": "API 서비스",
  "Put your service": "서비스를 레일 위에",
  "Register a live x402 endpoint and it appears on the Index automatically — we verify your HTTP 402 and XRPL config on the spot. No endpoint yet? Email us for a manual Directory listing.": "라이브 x402 엔드포인트(접속 주소)를 등록하면 인덱스에 자동으로 표시됩니다. HTTP 402 응답과 XRPL 설정은 그 자리에서 바로 확인해 드립니다. 아직 엔드포인트가 없으신가요? 이메일을 보내 주시면 검토 후 디렉터리에 직접 등록해 드립니다.",
  "Register an x402 endpoint": "x402 엔드포인트 등록",
  "auto-verified": "자동 검증",
  "We check your HTTP 402 configuration and XRPL requirements instantly, then publish you to the Agora and the Index.": "HTTP 402 설정과 XRPL 요건을 즉시 확인한 뒤, 아고라와 인덱스에 게시해 드립니다.",
  "Origin or API endpoint URL": "오리진 또는 API 엔드포인트 URL",
  "Display name": "표시 이름",
  "(optional)": "(선택 사항)",
  "e.g. ClawBank": "예: ClawBank",
  "Your merchant name on the Index. Skip it if your": "인덱스에 표시될 머천트 이름입니다. 생략 가능한 경우:",
  "already sets a top-level": "에 이미 설정된 최상위",
  "Verifying endpoint…": "엔드포인트 검증 중…",
  "Verify & register": "검증 및 등록",
  "Successfully registered {n} resources on the XRPL x402 network!": "XRPL x402 네트워크에 서비스 {n}개를 성공적으로 등록했습니다!",
  "Successfully registered {n} resource on the XRPL x402 network!": "XRPL x402 네트워크에 서비스 {n}개를 성공적으로 등록했습니다!",
  "Auto-discovery found {n} endpoints via .well-known/x402.": ".well-known/x402를 통해 자동 검색으로 엔드포인트 {n}개를 찾았습니다.",
  "Auto-discovery found {n} endpoint via .well-known/x402.": ".well-known/x402를 통해 자동 검색으로 엔드포인트 {n}개를 찾았습니다.",
  "Failed to register resource.": "서비스 등록에 실패했습니다.",
  "Failed endpoints": "실패한 엔드포인트",
  "Merchant logo": "머천트 로고",
  "Upload a small logo for the verified XRPL merchant address.": "검증된 XRPL 머천트 주소에 사용할 작은 로고를 올려 주세요.",
  "Logo": "로고",
  "Verified address": "검증된 주소",
  "Logo file": "로고 파일",
  "PNG, JPG, WebP, or GIF. Max 256KB.": "PNG, JPG, WebP 또는 GIF. 최대 256KB.",
  "Uploading logo…": "로고 업로드 중…",
  "Upload logo": "로고 업로드",
  "Logo uploaded successfully.": "로고가 업로드되었습니다.",
  "Use a PNG, JPG, WebP, or GIF logo.": "PNG, JPG, WebP 또는 GIF 형식의 로고를 사용해 주세요.",
  "Logo must be under 256KB.": "로고 파일은 256KB보다 작아야 합니다.",
  "Logo upload failed.": "로고 업로드에 실패했습니다.",
  "Network error occurred.": "네트워크 오류가 발생했습니다.",
  "Submit an origin URL to auto-discover": "오리진 URL을 제출하면",
  ", or a direct endpoint URL. Every registered endpoint must return": "를 자동 검색하거나, 직접 엔드포인트 URL을 제출할 수 있습니다. 등록된 모든 엔드포인트는 다음을 반환해야 합니다:",
  "with a valid": "응답과 유효한",
  "header containing": "헤더 — 포함 값:",
  "Tip: give every resource a": "팁: 모든 리소스에",
  "and": "및",
  "in your": "을 지정해 주세요 — 위치:",
  "(and a top-level": "(그리고 서비스용 최상위",
  "for your service) — we ingest them, so your listing reads properly instead of “Registered Resource”. Re-submit anytime to refresh; endpoints that leave your catalog are retired automatically.": "도 함께 지정) — 이 값을 수집해 쓰기 때문에, 목록이 “Registered Resource” 대신 올바른 이름으로 표시됩니다. 언제든 다시 제출하면 새로 고쳐지고, 카탈로그에서 빠진 엔드포인트는 자동으로 정리됩니다.",
  "No live endpoint yet?": "아직 라이브 엔드포인트가 없으신가요?",
  "If you don’t have an x402 endpoint live yet — or you just want a manual listing in the Directory — email us the details and we’ll add you after a quick review.": "아직 x402 엔드포인트를 운영하고 있지 않거나, 디렉터리에 수동 등록만 원하시나요? 자세한 내용을 이메일로 보내 주세요. 간단히 검토한 뒤 추가해 드립니다.",
  "Email {email}": "{email}로 이메일 보내기",
  "Address copied — paste it into your mail app.": "주소가 복사되었습니다. 메일 앱에 붙여 넣어 주세요.",
  "No mail app? Clicking copies the address.": "메일 앱이 없으신가요? 클릭하면 주소가 복사됩니다.",
  "Join · Facilitator": "참여 · Facilitator",
  "Register your": "Facilitator를",
  "facilitator": "등록하세요",
  "Submit your facilitator and its SourceTag. We index every XRPL Payment carrying that tag, so your settled volume appears on the Index. No ownership proof required.": "facilitator(결제 중개 서비스)와 그 SourceTag(거래에 찍히는 식별 번호)를 제출해 주세요. 해당 태그가 담긴 모든 XRPL Payment를 집계하므로, 정산한 거래량이 인덱스에 표시됩니다. 소유권 증명은 필요 없습니다.",
  "Facilitator name": "Facilitator 이름",
  "Acme Facilitator": "Acme Facilitator",
  "Facilitator URL": "Facilitator URL",
  "Networks (comma-separated)": "네트워크 (쉼표로 구분)",
  "Assets (comma-separated)": "자산 (쉼표로 구분)",
  "Description": "설명",
  "What your facilitator does.": "Facilitator가 하는 일을 적어 주세요.",
  "Registering…": "등록 중…",
  "Register facilitator": "Facilitator 등록",
  "Registered. Your SourceTag is now indexed — settled payments will appear on the Index.": "등록되었습니다. 이제 SourceTag 기준으로 집계하므로, 정산된 결제가 인덱스에 표시됩니다.",
  "Failed to register.": "등록에 실패했습니다.",
  "Network error.": "네트워크 오류입니다.",
  "Events": "이벤트",
  "Programming for the": "XRPL AI 커뮤니티를 위한",
  "XRPL AI community": "프로그램",
  "Fetch NFT collections held by an EVM wallet. The result includes the number of NFTs, the collection name and description of the NFTs.": "EVM 지갑이 보유한 NFT 컬렉션을 조회합니다. 조회 내역에는 NFT 개수, 컬렉션 이름, NFT에 대한 소개가 포함됩니다.",
  "Lucy token analysis service (XRPL x402)": "Lucy 토큰 분석 서비스(XRPL x402 기반)",
  "Returns a random interesting joke.": "재미있는 농담을 무작위로 제공합니다.",
  "Payment for Ask Surf chat via XRPL XRP": "XRPL XRP로 Ask Surf 사용을 위한 결제",
  "Access a curated selection of AI models through one simple router, starting at 0.003 RLUSD per request on XRPL. Prices vary by model and usage.": "하나의 라우터를 통해 엄선된 AI 모델을 이용할 수 있습니다. XRPL 기준 요청당 0.003 RLUSD부터 시작하며, 요금은 모델과 사용량에 따라 달라집니다.",
  "Single-shot lookup taking either a domain_id or an owner_address and returning the matching domain records with accepted credentials, decoded credential types and issuer labels. The agent-facing entry point when the caller already knows what it is looking for.": "domain_id 또는 owner_address를 입력하면 일치하는 도메인 레코드를 조회합니다. 승인된 자격 증명, 해독된 자격 증명 유형, 발급자 정보도 함께 반환합니다. 조회 대상을 이미 알고 있는 에이전트를 위한 진입 엔드포인트입니다.",
  "NOFA backtest and dry-run trading API": "NOFA 백테스트 및 드라이런(Dry Run) API",
  "Stock-backing analytics for LONG.xyz / Doppler tokens on Robinhood Chain": "Robinhood Chain의 LONG.xyz 및 Doppler 토큰을 위한 주식 기반 분석 서비스"
};
